name: dio_retry
description: A starting point for Dart libraries or applications.
version: 0.1.10-beta
homepage: https://github.com/iampato/dio_retry

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  logger: ^1.1.0
  meta: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
